---

- name: Copiamos el docker-compose.yml en los hosts Brothers
  copy:
    src: ../Pagina-Web 
    dest: /home/ubuntu

- name: Ejecutamos el docker-compose.yml
  shell:  'docker-compose up -d'
  args:
    chdir: /home/ubuntu/Pagina-Web 


- name: Damos permisos a apache 
  shell:  'sudo chown -R www-data:www-data *'
  args:
    chdir: /home/ubuntu/Pagina-Web /src/chat/