---
- hosts: Nagios 
  become: true
  roles: 
    - netdata

- hosts: Nagios 
  become: true
  roles: 
    - nagios-intalación

- hosts: Nrpe 
  become: true
  roles: 
    - nagios_cliente

- hosts: Nagios 
  become: true
  roles: 
    - nagios_config