---
- name: Lanzamos las instancias de Brother Ember
  ec2_instance:
          key_name: "{{ keypair }}" 
          security_group: "{{ SECURIRY_GROUP }}" 
          instance_type: "{{ instance_type}}"
          image_id: "{{ image }}" 
          wait: yes 
          region: "{{ region }}" 
          count: "{{ count }}"
          tags:
              Name: "{{INSTANCE_NAME_WWW1}}"
  register: ec2

- name: Lanzamos las instancias Brother Ahs
  ec2_instance:
          key_name: "{{ keypair }}" 
          security_group: "{{ SECURIRY_GROUP }}" 
          instance_type: "{{ instance_type}}"
          image_id: "{{ image }}" 
          wait: yes 
          region: "{{ region }}" 
          count: "{{ count }}"
          tags:
              Name: "{{INSTANCE_NAME_WWW2}}"
  register: ec2

- name: Lanzamos la instancia Balancer
  ec2_instance:
          key_name: "{{ keypair }}" 
          security_group: "{{ SECURIRY_GROUP3 }}" 
          instance_type: "{{ instance_type}}"
          image_id: "{{ image }}" 
          wait: yes 
          region: "{{ region }}" 
          count: "{{ count }}"
          tags:
              Name: "{{INSTANCE_NAME_BALANCER}}"
  register: ec2

- name: Lanzamos la instancia de NFS
  ec2_instance:
          key_name: "{{ keypair }}" 
          security_group: "{{ SECURIRY_GROUP4 }}" 
          instance_type: "{{ instance_type}}"
          image_id: "{{ image }}" 
          wait: yes 
          region: "{{ region }}" 
          count: "{{ count }}"
          tags:
              Name: "{{INSTANCE_NAME_SERVER}}"
  register: ec2

- name: Lanzamos la instancia Nagios
  ec2_instance:
          key_name: "{{ keypair }}" 
          security_group: "{{ SECURIRY_GROUP5 }}" 
          instance_type: "{{ instance_type}}"
          image_id: "{{ image }}" 
          wait: yes 
          region: "{{ region }}" 
          count: "{{ count }}"
          tags:
              Name: "{{INSTANCE_NAME_NAGIOS}}"
  register: ec2

- name: Lanzamos la instancia Mysql-server
  ec2_instance:
          key_name: "{{ keypair }}" 
          security_group: "{{ SECURIRY_GROUP7 }}" 
          instance_type: "{{ instance_type}}"
          image_id: "{{ image }}" 
          wait: yes 
          region: "{{ region }}" 
          count: "{{ count }}"
          tags:
              Name: "{{INSTANCE_NAME_MYSQL}}"
  register: ec2